services:
  app:
    image: ghcr.io/myrotvorets/codespaces/psb-api-microservice-node:latest@sha256:548c885733d3191a6c933ca2d579b470e2be65652874f1d2e07a9adc49852539
    depends_on:
      - otel-collector
      - jaeger
      - grafana
    environment:
      - NODE_ENV=development
      - NO_UPDATE_NOTIFIER=true
      - NPM_CONFIG_FUND=0
      - SUPPRESS_SUPPORT=1
      - HTTPS=0
      - PORT=3000
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=basic b3RlbDpvdGVs
      - npm_config_userconfig=/usr/src/service/.npmrc.local
      - KNEX_DATABASE=myrotvorets
      - KNEX_USER=myro
      - KNEX_PASSWORD=pass
      - KNEX_HOST=mariadb
      - KNEX_CONN_LIMIT=3
    restart: always
    volumes:
      - "../:/usr/src/service"
    working_dir: /usr/src/service

  mariadb:
    image: mariadb:11@sha256:1e669024fc94f626b9dc48bf47b29b5339cec203c28e61a3dc372991a345daf5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=myrotvorets
      - MYSQL_USER=myro
      - MYSQL_PASSWORD=pass
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest@sha256:34d37131366c5aa84e1693dbed48593ed6f95fb450b576c1a7a59d3a9c9e8802
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.128.0@sha256:1ab0baba0ee3695d823c46653d8a6e8894896e668ce8bd7ebe002e948d827bc7
    command:
      - "--config=/etc/otel-collector-config.yaml"
    depends_on:
      - victoriametrics
      - jaeger
      - loki
    restart: always
    volumes:
      - ./.docker/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  jaeger:
    image: ghcr.io/myrotvorets/codespaces/jaeger:latest@sha256:2c8f84186ac25947c1c1409c050b2544c587ee2ddf0a87f2616b86961509f147
    restart: always
    volumes:
      - jaegerdata:/badger

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.112.0@sha256:98363e91a586c6cf095833bbb284eddc303d606aa018d6757a74e35a4a4e9afb
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
    restart: always
    volumes:
      - vmdata:/storage

  loki:
    image: grafana/loki:3.4.2@sha256:58a6c186ce78ba04d58bfe2a927eff296ba733a430df09645d56cdc158f3ba08
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    restart: always

  grafana:
    image: grafana/grafana:11.5.2@sha256:8b37a2f028f164ce7b9889e1765b9d6ee23fec80f871d156fbf436d6198d32b7
    depends_on:
      - victoriametrics
      - loki
    restart: always
    volumes:
      - grafanadata:/var/lib/grafana
      - ./.docker/grafana/provisioning/:/etc/grafana/provisioning/
      - ./.docker/grafana/dashboards/app.json:/var/lib/grafana/dashboards/app.json

  swagger:
    image: swaggerapi/swagger-ui:v5.25.3@sha256:77f03599e686f6411258bce4081cc32fd981eff6c332f0db1aaeae859e08a1f1
    environment:
      - SWAGGER_JSON_URL=/specs/dzhura-private.yaml
      - BASE_URL=/swagger
      - DISPLAY_REQUEST_DURATION=true
      - DEFAULT_MODELS_EXPAND_DEPTH=100
      - DEFAULT_MODEL_EXPAND_DEPTH=100
      - DEEP_LINKING=true
      - VALIDATOR_URL=none

volumes:
  grafanadata:
  jaegerdata:
  mysql_data:
  vmdata:
