services:
  dzhura:
    build:
      context: .docker/dzhura
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NO_UPDATE_NOTIFIER=true
      - NPM_CONFIG_FUND=0
      - SUPPRESS_SUPPORT=1
      - HTTPS=0
      - PORT=3000
      - ENABLE_TRACING=1
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - HAVE_SWAGGER=true
      - MYSQL_DATABASE=myrotvorets
      - MYSQL_USER=myro
      - MYSQL_PASSWORD=pass
      - MYSQL_HOST=mariadb
      - MYSQL_CONN_LIMIT=3
    restart: always
    volumes:
      - "../:/usr/src/service"
    working_dir: /usr/src/service

  mariadb:
    image: mariadb:11@sha256:2403cc521634162f743b5179ff5b35520daf72df5d9e7e397192af685d9148fd
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=myrotvorets
      - MYSQL_USER=myro
      - MYSQL_PASSWORD=pass
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest@sha256:f762276d79d2f18ae7fe28c79ee25a0a3b3dba9dc92ed695a3e88d613b3e6bde
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    restart: always

  zipkin:
    image: openzipkin/zipkin:latest@sha256:5fd55e6a109233b36d419d7fd2449588d17a6e4da7ed7a3fd0d09c86f1c75a15
    restart: always

  swagger:
    image: swaggerapi/swagger-ui:latest@sha256:c17153d23b81490d9b1d56bb26448b44b2fd43e46e8656ccb6af34eceb291a79
    environment:
      - SWAGGER_JSON_URL=/specs/dzhura-private.yaml
      - BASE_URL=/swagger
      - DISPLAY_REQUEST_DURATION=true
      - DEFAULT_MODELS_EXPAND_DEPTH=100
      - DEFAULT_MODEL_EXPAND_DEPTH=100
      - DEEP_LINKING=true
      - VALIDATOR_URL=none
    restart: always

volumes:
  mysql_data:
