name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        node:
          - { name: Current, version: current }
          - { name: LTS,     version: lts/* }
    steps:
      - name: Check out the code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true

      - name: Build and test
        uses: myrotvorets/composite-actions/build-test-nodejs@d48d1c16e5782ea32f56fe24da600ca2028ed8b1 # master
        with:
          node-version: ${{ matrix.node.version }}
          registry-url: https://npm.pkg.github.com
